### ISSUE TITLE
Next Page button not working on firefox

### ISSUE THREAD

**Issue by kkhan01** [radlinskii/octo-board#26]
Title says it all. The button works fine on chrome/ chromium, but does not on firefox .

**Comment by radlinskii** [comment]
Thank you @kkhan01 for creating this issue. I was able to reproduce it.
The problem can be found on [stackoverflow](https://stackoverflow.com/questions/16280684/nesting-a-inside-button-doesnt-work-in-firefox).

The solution is to change the `button` tag to `div` inside `/templates/content/search.html`.
Remember that `div` is usually displayed as `block` and button was a `inline-block`.

**Comment by Esslamb** [comment]
I could have a look at this :)
